app:
  comments_limit: 20
  users_limit: 10
  photos_limit: 5
  com_lim: 2
  like_lim: 2
  folow_lim: 2
  friend_lim: 2
  image_dir: /system/photos/
  image_name: original
  image_ext: .jpg
  photo_sizes:
    width: 200
    height: 200
  avatar:
    upload_dir: /system/avatars/
    b:
      width: 100
      height: 100
facebook:
  url:
    graph: https://graph.facebook.com

